- name: Script orchestration with user permission
  hosts: local
  tasks:
    - name: Organization of files by extensions
      script: ~/Documentos/DevOps-Toolbox/scripts/debian/files-organization.sh
      
    - name: Backup of files of main directories
      script: ~/Documentos/DevOps-Toolbox/scripts/debian/files-backup.sh