pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Build"'
            }
        }
        stage('Test'){
            steps {
                sh 'echo "Test"'
                junit 'reports/**/*.xml'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploy' //
            }
        }
    }
}