- name: Script orchestration with administrator permission
  hosts: local
  become: yes
  tasks:
    - name: Update and upgrade packages, remove orphaned dependencies and clean old packages
      script: ~/Documentos/DevOps-Toolbox/scripts/fedora/update-clean.sh

    - name: Install wget, ca-certificates, curl, gnupg, lsb-release
      dnf:
       name:
       - wget
       - ca-certificates
       - curl
       - gnupg
       - lsb-release